import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const contracts = [
  {
    artifactPath: path.join(repoRoot, "contracts", "out", "EvaThesisProtocol.sol", "EvaThesisProtocol.json"),
    exportName: "evaThesisProtocolAbi",
    filename: "evaThesisProtocolAbi.ts",
  },
];

for (const contract of contracts) {
  if (!fs.existsSync(contract.artifactPath)) {
    continue;
  }

  const artifact = JSON.parse(fs.readFileSync(contract.artifactPath, "utf8"));
  const fileBody = `// This file is generated by scripts/generate-eva-abi.mjs
// Do not edit by hand. Re-run \`node scripts/generate-eva-abi.mjs\` after contract changes.

export const ${contract.exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  for (const target of [
    path.join(repoRoot, "frontend", "lib", "generated", contract.filename),
    path.join(repoRoot, "backend", "src", "generated", contract.filename),
  ]) {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, fileBody);
  }
}
