import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(new URL("..", import.meta.url).pathname);
const artifactPath = path.join(repoRoot, "contracts", "out", "EvaTrustGraph.sol", "EvaTrustGraph.json");
const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

const fileBody = `// This file is generated by scripts/generate-eva-abi.mjs
// Do not edit by hand. Re-run \`node scripts/generate-eva-abi.mjs\` after contract changes.

export const evaTrustGraphAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

for (const target of [
  path.join(repoRoot, "frontend", "lib", "generated", "evaTrustGraphAbi.ts"),
  path.join(repoRoot, "backend", "src", "generated", "evaTrustGraphAbi.ts")
]) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, fileBody);
}
